config/routes.rb
require File.expand_path("../../lib/authenticated_user", __FILE__)

Rails.application.routes.draw do

  get 'sessions/new'

  get       'activities' => 'activities#index'
  resources :activities
  post      'items/new' => 'items#new'
  resources :items

  post      'houses/:id/edit' => 'houses#edit'
  post      'houses/:id/remove/:user_id' => 'houses#remove', as: :remove_house
  post      'houses/:id/promote/:user_id' => 'houses#promote', as: :promote_house
  resources :houses

  post      'users/:id/edit' => 'users#edit'
  resources :users

	get				'login' => 'sessions#new'
	post			'login' => 'sessions#create'
	delete		'logout' => 'sessions#destroy'
  get       'logout' => 'sessions#destroy'

  post  'events/new' => 'events#new'
  post  'events/export' => 'events#export', as: :export_event
  post  'events/store' => 'events#store', as: :store_event
  post   'events/import' =>  'events#import', as: :import_event
  resources :events

  get      'items/:id/increase' => 'items#increase', as: :increase_item
  get      'items/:id/decrease' => 'items#decrease', as: :decrease_item
  get       'items/:id/movetoshop' => 'items#addtoshop', as: :shop_item
  get       'items/:id/movetoinventory' => 'items#addtoinventory', as: :inv_item

  post  'notes/new' => 'notes#new'
  resources :notes do
    resources :comments
  end

  resources :permissions
  resources :transactions

  post 'polls/new' => 'polls#new'
  resources :polls
  resources :votes, only: [:create]

  get 'users/new'

  get 'items/new'

  root :to => 'pages#home'

  get "financial" => 'transactions#index'
  get "account" => 'pages#account'
  get "register" => 'pages#signup'

  get 'invitation' => 'invitation#get'
  post 'invitation/create' => 'invitation#create'
  post 'invitation/delete' => 'invitation#delete'
  post 'invitation/email' => 'invitation#email'
  get 'invitation/:token' => 'invitation#view'
  get 'i/:token' => 'invitation#view'

end

app/models/note.rb
class Note < ActiveRecord::Base

	include PublicActivity::Model
	tracked owner: ->(controller, model) { controller && controller.current_user }

	has_one :poll
  belongs_to :user
  has_many :users
	has_many :comments
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true
  has_many :permissions, as: :permissable, dependent: :destroy
  accepts_nested_attributes_for :permissions

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
  	@note = Note.new
    @note.permissions.build
  end

  def create
  	@note = current_user.notes.build(note_params)
    @note.house_id = current_user.relationship.house_id
  	if @note.save
      @perm_user = @note.permissions.create(user_id: current_user.id, level: 0)
  	  flash[:success] = "Note Created"
      redirect_to notes_path
  	else
  	  render 'new'
  	 end
  end

  def destroy
    @note.destroy
    flash[:success] = "Note deleted"
    redirect_to notes_path
  end

  def index
    h = House.find(current_user.relationship.house_id)
  	@notes = h.notes.paginate(page: params[:page])
    @polls = h.polls

    @collect = @notes + @polls
    puts @collect
    @collect = (@collect.sort_by &:created_at).reverse
    puts @collect
    @activities = PublicActivity::Activity.order("created_at desc")
  end

  def edit
    @note = Note.find(params[:id])
  end

  def show
    @notes = Note.paginate(page: params[:page])
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    permparams = (params[:note][:permission].permit!)
    permparams.each_key do |key|
      perm = Permission.find(key)
      perm.level = permparams[key][:level]
      perm.save
    end

    if @note.update_attributes(note_params)
      flash[:success] = "Note updated"
      redirect_to notes_path
    else
      render 'edit'
    end
  end

  private

    def note_params
      params.require(:note).permit(:id, :content, :lastEditedBy, :title,
      permissions_attributes: [:id, :user_id, :level])
    end

    def correct_user
      @note = Note.find_by(id: params[:id])
      if @note.nil?
        flash[:danger] = "You are not allowed to perform that task on that note."
        redirect_to notes_path
      end
    end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :title, placeholder: "Note Title..." %>
    <%= f.text_area :content, placeholder: "Compose new Note..." %>
  </div>
  <% if u == 0 %>
    <%= render 'permission_new', f: f, :type => 0 %>
  <% else %>
    Edit User Permissions
    <%= render 'permission_edit', f: f, obj: @note, :type => 0 %>
    <%= f.hidden_field :lastEditedBy, value: current_user.id %>
  <% end %>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/notes/_note.html.erb
<ol class="notes">
  <%= render @notes %>
  <%= link_to "Write a Note", new_note_path, class: "btn btn-primary btn-lg" %
</ol>

app/views/notes/edit.html.erb
<% provide(:title, 'Edit a Note') %>
<h1>Noteboard</h1>

<%= render 'form', :u => 1 %>

app/views/notes/index.html.erb
<% provide(:title, 'Noteboard') %>

<h1>Noteboard</h1>

	<%= will_paginate %>
			<% @collect.each do |obj| %>
			 	<% if obj.has_attribute?(:title) %>
					<% note = obj %>

						<% if note.permissions.find_by user_id: current_user.id %>
							<% perm = note.permissions.find_by user_id: current_user.id %>
						<% else %>
							<% perm = note.permissions.first %>
						<% end %>

						<% if perm.level < 4 %>
							<div class="col-md-4">
								<div class="message">
									<h3 class="message-title"><%= note.title %></h3>
									<%= link_to "view Note", note_path(note), class: "btn btn-custom" %>

								</div>
							</div>
						<% end %>

				<% else %>

					<% poll = obj %>
					  <div class="col-md-4">
							<div class="message">
					    <h3 class="message-title"><%= poll.topic %> <small>(voted: <%= poll.votes_summary %>)</small></h3>
							<p style="color:WhiteSmoke;">
							<% if poll.top_voted != nil %>
								Currently Winning: <%= poll.top_voted.title %> with <%= poll.top_voted.votes.count %> votes!</h4>
							</p>
							<% end %>
							<div class="btn-group">
							<% unless current_user.voted_for?(poll) %>
					    	<%= link_to 'Vote', poll_path(poll), class: 'btn btn-primary btn block' %>
							<% else %>
								<%= link_to 'View', poll_path(poll), class: 'btn btn-primary btn block' %>
							<% end %>

					      <%= link_to 'Edit', edit_poll_path(poll), class: 'btn btn-default' %>
					      <%= link_to 'Delete', poll_path(poll),
					                  method: :delete,
					                  class: 'btn btn-danger', data: {confirm: 'Are you sure?'} %>
													</div>
					    </div>
					  </div>

				<% end %>
			<% end %>
</br>
<%= button_to "Create a Note", new_note_path, class: "btn btn-primary" %>
<%= button_to "Create a Poll", new_poll_path, class: "btn btn-primary" %>

app/views/notes/new.html.erb
<% provide(:title, 'Create a Note') %>
<h1>Noteboard</h1>

<%= render 'form', :u => 0 %>

app/views/notes/show.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="message-show">
    <% if @note.permissions.find_by user_id: current_user.id %>
      <% perm = @note.permissions.find_by user_id: current_user.id %>
    <% else %>
      <% perm = @note.permissions.first %>
    <% end %>

    <% if perm.level < 4 %>

      <h2 class="message-title"><%= @note.title %></h2>
      <% if @note.lastEditedBy == nil %>
      <p class="message-posted-by">Posted by <%= @note.user.name %> <%= time_ago_in_words(@note.created_at) %> ago</p>
      <% else %>
      <p class="message-posted-by">Last edited by: <%= User.find(@note.lastEditedBy).name %> <%= time_ago_in_words(@note.updated_at) %> ago</p>
      <% end %>

      <p class="message-desc"><%= @note.content %></p>

    <% end %>

    <%= render @note.comments %>

    <h3 class="reply-to-msg">Comment on notes:</h3>
    <%= render 'comments/form' %>

    <br>

    <div class="links btn-group">
      <div align="right">
        <%= link_to "Back", notes_path, class: "btn btn-default" %>
        <% if perm.level < 3 %>
          <%= link_to "Edit", edit_note_path(@note), class: "btn btn-default" %>
        <% end %>
        <% if perm.level < 2 %>
          <%= link_to "Delete", @note, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-default" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/notes/tempdex.erb
<% provide(:title, 'Noteboard') %>
<h1>Noteboard</h1>

<%= will_paginate %>
	<ul class="notes">
	  <% House.find(current_user.relationship.house_id).notes.each do |note| %>
	    <li>
	      <%= note.content %>
	      <div align="right">
	      	<% if note.user_id == current_user.id %>
	      		<%= link_to "Edit", edit_note_path(note) %>
	      		<%= link_to "Delete", note, method: :delete, data: { confirm: "You sure?" } %>
	      	<% end %>
	      	Created by: <%= User.find(note.user_id).name %>
	      </div>
	    </li>
	  <% end %>
	</ul>
<%= will_paginate %>

<%= button_to "Create a Note", new_note_path, class: "btn btn-primary" %>