config/routes.rb
require File.expand_path("../../lib/authenticated_user", __FILE__)

Rails.application.routes.draw do

  get 'sessions/new'

  get       'activities' => 'activities#index'
  resources :activities
  post      'items/new' => 'items#new'
  resources :items

  post      'houses/:id/edit' => 'houses#edit'
  post      'houses/:id/remove/:user_id' => 'houses#remove', as: :remove_house
  post      'houses/:id/promote/:user_id' => 'houses#promote', as: :promote_house
  resources :houses

  post      'users/:id/edit' => 'users#edit'
  resources :users

	get				'login' => 'sessions#new'
	post			'login' => 'sessions#create'
	delete		'logout' => 'sessions#destroy'
  get       'logout' => 'sessions#destroy'

  post  'events/new' => 'events#new'
  post  'events/export' => 'events#export', as: :export_event
  post  'events/store' => 'events#store', as: :store_event
  post   'events/import' =>  'events#import', as: :import_event
  resources :events

  get      'items/:id/increase' => 'items#increase', as: :increase_item
  get      'items/:id/decrease' => 'items#decrease', as: :decrease_item
  get       'items/:id/movetoshop' => 'items#addtoshop', as: :shop_item
  get       'items/:id/movetoinventory' => 'items#addtoinventory', as: :inv_item

  post  'notes/new' => 'notes#new'
  resources :notes do
    resources :comments
  end

  resources :permissions
  resources :transactions

  post 'polls/new' => 'polls#new'
  resources :polls
  resources :votes, only: [:create]

  get 'users/new'

  get 'items/new'

  root :to => 'pages#home'

  get "financial" => 'transactions#index'
  get "account" => 'pages#account'
  get "register" => 'pages#signup'

  get 'invitation' => 'invitation#get'
  post 'invitation/create' => 'invitation#create'
  post 'invitation/delete' => 'invitation#delete'
  post 'invitation/email' => 'invitation#email'
  get 'invitation/:token' => 'invitation#view'
  get 'i/:token' => 'invitation#view'

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
 	before_action :logged_in_user
 	before_action :member_of_house, except: [:new, :create]
 	before_action :is_admin, only: [:edit, :update, :remove]

 	def show
		@house = House.find(params[:id])
	end
	def new
		@house = House.new
  	end
	def create
		@house = House.new(house_params)
		@house.permissions.build

		@house.add_user(current_user)
		
		if @house.save
			@house.permissions.create(user_id: 0, level: 1)
			@house.permissions.create(user_id: current_user.id, level: 0)
			if current_user.save(validate: false)
				flash[:success] = "Welcome to your new Home, #{current_user.name}"
			else
				flash[:notice] = "Unable to save user"
			end
			redirect_to @house
		else
			render 'new'
		end
	end

	def edit
		@house = House.find(params[:id])
	end

	def update
		@house = House.find(params[:id])
		if @house.update_attributes(house_params)
			flash[:success] = "House information updated"
			redirect_to @house
		else
			render 'edit'
		end
	end

	def remove
		@house = House.find(params[:id])
		@house.relationships.find_by(user_id: params[:user_id]).destroy
		flash[:success] = "User Removed"
		redirect_to @house
	end

	def promote
		@house = House.find(params[:id])
		@house.permissions.find_by(user_id: current_user.id).destroy
		@house.permissions.create(user_id: params[:user_id], level: 0)
		flash[:success] = "User promoted to Admin"
		redirect_to @house
	end

	private
		def house_params
			params.require(:house).permit(:name, :street, :city, :state, :zip)
		end

		def is_admin
			@house = House.find(params[:id])
			if @house.permissions.find_by user_id: current_user.id
				perm = @house.permissions.find_by user_id: current_user.id
			else
				perm = @house.permissions.first
			end

			unless perm.level == 0
				flash[:danger] = "You must be the house administrator to view this page"
				redirect_to @house
			end
		end

		def member_of_house
			@house = House.find(params[:id])
			unless @house.relationships.find_by(user_id: current_user.id)
				flash[:danger] = "You are not a member of that house and may not perform that task"
				redirect_to root_path
			end
		end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/edit.html.erb
<% provide(:title, "Edit house") %>
<h1>Update your house info</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<%= form_for(@house) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
    <ul>  
      <% @house.users.each do |user| %>
	      <% if user.id != current_user.id %>
	        <li>  
	          <%= user.name %>
	          <%= link_to "Remove", remove_house_path(:user_id => user.id), method: :post, data: {confirm: "Are you sure?"} %>
	          <%= link_to "Make Admin", promote_house_path(:user_id => user.id), method: :post, data: {confirm: "This will remove your admin priveleges. Are you sure?"} %>
	        </li>
	      <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/houses/new.html.erb
<% provide(:title, 'Create a House') %>
<h1>Create a House</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@house) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

  			<%= f.label :street %>
			<%= f.text_field :street,  class: 'form-control' %>

			<%= f.label :city %>
			<%= f.text_field :city, class: 'form-control' %>

			<%= f.label :state %>
			<%= f.text_field :state, class: 'form-control' %>

			<%= f.label :zip %>
			<%= f.text_field :zip, class: 'form-control' %>

			<%= f.submit "Create a House", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/houses/show.html.erb
<h1 class="center"><%= @house.name %></h1>
<div class="center">
	<%= @house.street %><br/>
	<%= @house.city %><br/>
	<%= @house.state %><br/>
	<%= @house.zip %><br/
	<!-- Only shows the first user of the house using this syntax -->
	<br/>
	<% @house.users.each do |user| %>
	    <div class="center"><%= user.name %></div>
	<% end %>

<br/>
<h4>Invite other users!</h4>
<h4>Manage your invites <a href="<%= request.base_url + "/invitation/" %>">here.</a></div></h4>

	<% if @house.permissions.find_by user_id: current_user.id %>
		<% perm = @house.permissions.find_by user_id: current_user.id %>
	<% else %>
		<% perm = @house.permissions.first %>
	<% end %>

	<% if perm.level == 0 %>
		<%= button_to "Edit House Info", edit_house_path(@house), class: "btn btn-primary" %>
	<% end %>
</div>