config/routes.rb
require File.expand_path("../../lib/authenticated_user", __FILE__)

Rails.application.routes.draw do

  get 'sessions/new'

  get       'activities' => 'activities#index'
  resources :activities
  post      'items/new' => 'items#new'
  resources :items

  post      'houses/:id/edit' => 'houses#edit'
  post      'houses/:id/remove/:user_id' => 'houses#remove', as: :remove_house
  post      'houses/:id/promote/:user_id' => 'houses#promote', as: :promote_house
  resources :houses

  post      'users/:id/edit' => 'users#edit'
  resources :users

	get				'login' => 'sessions#new'
	post			'login' => 'sessions#create'
	delete		'logout' => 'sessions#destroy'
  get       'logout' => 'sessions#destroy'

  post  'events/new' => 'events#new'
  post  'events/export' => 'events#export', as: :export_event
  post  'events/store' => 'events#store', as: :store_event
  post   'events/import' =>  'events#import', as: :import_event
  resources :events

  get      'items/:id/increase' => 'items#increase', as: :increase_item
  get      'items/:id/decrease' => 'items#decrease', as: :decrease_item
  get       'items/:id/movetoshop' => 'items#addtoshop', as: :shop_item
  get       'items/:id/movetoinventory' => 'items#addtoinventory', as: :inv_item

  post  'notes/new' => 'notes#new'
  resources :notes do
    resources :comments
  end

  resources :permissions
  resources :transactions

  post 'polls/new' => 'polls#new'
  resources :polls
  resources :votes, only: [:create]

  get 'users/new'

  get 'items/new'

  root :to => 'pages#home'

  get "financial" => 'transactions#index'
  get "account" => 'pages#account'
  get "register" => 'pages#signup'

  get 'invitation' => 'invitation#get'
  post 'invitation/create' => 'invitation#create'
  post 'invitation/delete' => 'invitation#delete'
  post 'invitation/email' => 'invitation#email'
  get 'invitation/:token' => 'invitation#view'
  get 'i/:token' => 'invitation#view'

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	validates :user_id, presence: true
	validates :name, presence: true
	validates :description, presence: false
	validates :start_time, presence: true
	validates :end_time, presence: true
	has_many :permissions, as: :permissable, dependent: :destroy
	accepts_nested_attributes_for :permissions
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :logged_in_user

	def new
		@event = Event.new
		@event.permissions.build
	end

	def create
		@event = current_user.events.build(event_params)
		if @event.save
			@event.permissions.create(user_id: 0, level: 2)
			@perm_user = @event.permissions.create(user_id: current_user.id, level: 0)
			flash[:success] = "Event created"
			redirect_to events_path
		else
			render 'new'
		end
	end

	def index
		@events = House.find(current_user.relationship.house_id).events
		@date = params[:date] ? Date.parse(params[:date]) : Date.today
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])
		permparams = (params[:event][:permission].permit!)
		permparams.each_key do |key|
			perm = Permission.find(key)
			perm.level = permparams[key][:level]
			perm.save
		end

		if @event.update_attributes(event_params)
			flash[:success] = "Event successfully updated"
			redirect_to events_path
		else
			render 'edit'
		end
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		flash[:success] = "Event successfully deleted"
		redirect_to events_path
	end

	def export
		@events = House.find(current_user.relationship.house_id).events
		file = ''
		file << "BEGIN:VCALENDAR\n"
		@events.each do |event|
			if event.permissions.find_by user_id: current_user.id
				perm = event.permissions.find_by user_id: current_user.id
			else
				perm = event.permissions.find_by user_id: 0
			end
			if perm.level == 0 || perm.level == 3
				file << "BEGIN:VEVENT\nDTSTART:" + event.start_time.strftime("%Y%m%dT%H%M%S") + "\nDTEND:" + event.end_time.strftime("%Y%m%dT%H%M%S") + "\nDESCRIPTION:" + event.description + "\nSUMMARY:" + event.name + "\nEND:VEVENT\n"
			end
		end
		file << "END:VCALENDAR"
		send_data file, :filename => current_user.name + 'Schedule.ics', :type => 'text/calendar'
	end

	def import
	end

	def store
		uploaded_file = params[:file]
		if uploaded_file.nil?
			flash[:danger] = "No file was selected for upload"
			render 'import' and return
		end
		file_content = uploaded_file.read
		lines = file_content.split("\n");
		if lines.first.strip != 'BEGIN:VCALENDAR'
			flash[:danger] = "File was not .ics format."
			render 'import'
		else
			count = 0
			inevent = false
			lines.each do |line|
				line = line.strip
				parts = line.split(":")
				if parts[0] == "BEGIN" && parts[1] == "VEVENT"
					inevent = true
					@event = Event.new
					@event = current_user.events.build
				elsif parts[0] == "DTSTART" && inevent
					@event.start_time = DateTime.strptime(parts[1], "%Y%m%dT%H%M%S")
				elsif parts[0] == "DTEND" && inevent
					@event.end_time = DateTime.strptime(parts[1], "%Y%m%dT%H%M%S")
				elsif parts[0] == "DTSTART;VALUE=DATE" && inevent
					@event.start_time = DateTime.strptime(parts[1], "%Y%m%d")
				elsif parts[0] == "DTEND;VALUE=DATE" && inevent
					@event.end_time = DateTime.strptime(parts[1], "%Y%m%d")
				elsif parts[0] == "DESCRIPTION" && inevent
					@event.description = parts[1]
				elsif parts[0] == "SUMMARY" && inevent
					@event.name = parts[1]
				elsif parts[0] == "END" && parts[1] == "VEVENT"
					inevent = false
					if @event.save
						count += 1
						@event.permissions.create(user_id: 0, level: 2)
						@perm_user = @event.permissions.create(user_id: current_user.id, level: 0)
					else
						puts @event.to_json
						flash[:danger] = "Event could not save correctly"
						render 'import' and return
					end
				end
			end
			flash[:success] = "#{count} " + 'event'.pluralize(count) + ' added.'
			redirect_to events_path
		end
	end

	private
		def event_params
			params.require(:event).permit(:name, :description, :start_time, :end_time, permissions_attributes: [:id, :user_id, :level])
		end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<% provide(:title, 'Edit Event') %>
<h1><%= @event.name %></h1>

<% if @event.permissions.find_by user_id: current_user.id %>
  <% perm = @event.permissions.find_by user_id: current_user.id %>
<% else %>
  <% perm = @event.permissions.find_by user_id: 0 %>
<% end %>

<% if perm.level == 0 %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= simple_form_for(@event) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>

        <%= f.input :start_time, :as => :datetime_picker %>

        <%= f.input :end_time, :as => :datetime_picker %>

        <%= render 'permission_edit', f: f, obj: @event, :type => 1 %>

        <%= f.submit "Update Event", class: "btn btn-primary" %>
      <% end %>
      <div class="center">
        <%= link_to "Delete", @event, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% elsif perm.level == 1 %>
  <h2>Do you accept this invitation?</h2>
  <%= simple_form_for(@event) do |f| %>
    <%= f.fields_for perm, index: perm.id do |perm_form| %>
      <%= perm_form.hidden_field :user_id, value: current_user.id %>
      <%= perm_form.select :level, [["Accept", 3], ["Decline", 2]] %>
    <% end %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
<% elsif perm.level == 3 %>
  <div class="row">
    <div class="center">
      <%= @event.description %><br/>
      <%= @event.start_time %><br/>
      <%= @event.end_time %><br/>
      <%= simple_form_for(@event) do |f| %>
        <%= f.fields_for perm, index: perm.id do |perm_form| %>
          <%= perm_form.hidden_field :level, value: 2 %>
        <% end %>
        <%= f.submit "Remove", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/events/import.html.erb
<%= form_tag store_event_path, :multipart => true do %>
	<br /><div class="center"><label for="file">Import Calendar File</label></div><%= file_field_tag "file", accept: 'text/calendar' %>
	<%= submit_tag "Import", class: "btn btn-primary" %>
<% end %>

app/views/events/index.html.erb
<% provide(:title, 'Schedule') %>
<h1>Schedule</h1>

<div id="events">
	<h2 id="month">
		<%= link_to "<", date: @date.prev_month %>
		<%= @date.strftime("%B %Y") %>
		<%= link_to ">", date: @date.next_month %>
	</h2>
	<%= calendar @date do |date| %>
		<%= date.day %>
		<ul>
			<% @events.find_all{|event| event.start_time.to_date <= date && event.end_time.to_date >= date}.each do |event| %>
				<% if event.permissions.find_by user_id: current_user.id %>
					<% perm = event.permissions.find_by user_id: current_user.id %>
				<% else %>
					<% perm = event.permissions.find_by user_id: 0 %>
				<% end %>
				<% if perm.level == 0 || perm.level == 3 %>
					<li>
						<%= link_to event.name, edit_event_path(event) %>
					</li>
				<% end %>
			<% end %>
		</ul>
	<% end %>

	<h3>Pending Invites:</h3>
	<ul>
		<% @events.each do |event| %>
			<% if event.permissions.find_by user_id: current_user.id %>
				<% perm = event.permissions.find_by user_id: current_user.id %>
			<% else %>
				<% perm = event.permissions.find_by user_id: 0 %>
			<% end %>
			<% if perm.level == 1 %>
				<li>
					<%= event.name %><br/>
					<%= event.description %><br/>
					<%= event.start_time %><br/>
					<%= event.end_time %><br/>
					<%= link_to "Reply", edit_event_path(event) %>
				</li>
			<% end %>
		<% end %>
	</ul>
</div>

<%= button_to "Create an Event", new_event_path, class: "btn btn-primary" %>
<%= button_to "Export Calendar", export_event_path, class: "btn btn-primary" %>
<%= button_to "Import a Calendar", import_event_path, class: "btn btn-primary" %>

app/views/events/new.html.erb
<% provide(:title, 'Create Event') %>
<h1>Create Event</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= simple_form_for(@event) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>

        <%= f.input :start_time, :as => :datetime_picker %>

        <%= f.input :end_time, :as => :datetime_picker %>
      </div>
      <%= render 'permission_new', f: f , :type => 1 %>
      <%= f.submit "Create Event", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>